authorization:
  type: AUTHORIZATION_TYPE_APP_USERS
blocks:
  - name: Step1
    step:
      integration: javascript
      javascript:
        body:
          path: ./step1.js
metadata:
  name: API1
  organization: 8f0f1693-c495-4f74-9f16-2c0ee665cb3c
  timestamps:
    updated: 2025-06-24T14:26:04.308Z
trigger:
  application:
    id: ec3168cb-f52a-4f56-8b7d-a12edea92884
    pageId: c76708d3-2183-4c5e-b0e1-6624f37bd385
