authorization:
  type: AUTHORIZATION_TYPE_APP_USERS
blocks:
  - name: Step1
    step:
      integration: 86413bc4-a725-4597-950d-110e816e3f01
      postgres:
        body: |-
          `-- You can use SQL to query data (ex. SELECT * FROM orders;)
          select * from orders;
          `
        operation: run_sql
        usePreparedSql: true
metadata:
  name: API1
  organization: 8f0f1693-c495-4f74-9f16-2c0ee665cb3c
  timestamps:
    updated: 2025-06-24T16:12:37.234Z
trigger:
  application:
    id: ecf28d72-debe-4bdb-9177-f029ca7b5ee7
    pageId: 0f922733-e7c7-44ba-b7ed-6e157e05e3d0
